### ISSUE TITLE
Push to the same branch

### ISSUE THREAD

**Issue by alexdesignworks** [integratedexperts/robo-git-artefact#2]
Add support for pushing artefact to the same branch with resolving of tags.

Due to complexity of tags and references resolution, this implementation should support only the most straightforward case:
- do not preserve commit history, but rather squash commits and provide commits history in the message of this squashed commit.
- push tags from the last commit only. if tags already exist on remote - fail deployment. A user would have to resolve tags manually.

**Comment by zeyus** [comment]
see https://github.com/integratedexperts/robo-git-artefact/pull/3

**Comment by alexdesignworks** [comment]
implemented in PR #7
